name: "R-CMD-check (Windows: 4.4.0, latest)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: [ "4.4.0", "4.4.3", "latest" ]

    steps:
      - name: "STEP 1: Check out repository"
        uses: actions/checkout@v4

      - name: "STEP 2: Set up R ${{ matrix.r-version }}"
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: "STEP 3: Install R package dependencies"
        run: |
          install.packages("pak", repos = "https://cloud.r-project.org")
          pak::pak("rcmdcheck")
          pak::pak("local::.")
        shell: Rscript {0}

      - name: "STEP 4: Run R CMD check"
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
