name: R-CMD-check (Windows: 4.4.0, 4.4.1, 4.4.2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: [ "4.4.0", "4.4.1", "4.4.2" ]

    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up the specified R version
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # 3. Install dependencies
      #    - This step will install your package's dependencies based on
      #      the DESCRIPTION file
      #    - `extra-packages` can install anything needed for checks (like rcmdcheck)
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      # 4. Run R CMD check (via rcmdcheck package)
      - name: Run R CMD check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
